# Generated by Django 2.0.7 on 2018-07-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jobs',
            new_name='job',
        ),
    ]
